name: Build and Package on Every Push

on:
#  push:
#    branches:
#      - '**'
#  pull_request:
#    branches:
#      - '**'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build and Package Linux Executable

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ \
          cmake \
          libssl-dev \
          libpcre2-dev \
          pkg-config \
          wget \
          tar \
          gzip

    - name: Install C++ libraries via vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        # 不带包名，vcpkg 会读取 vcpkg.json
        ./vcpkg/vcpkg install
        ./vcpkg/vcpkg integrate install

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release -j$(nproc)

    - name: Package executable
      run: |
        cd build
        TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
        COMMIT_SHORT=$(git rev-parse --short HEAD)
        mkdir -p "Netease_sensitive_word_linux_${COMMIT_SHORT}_${TIMESTAMP}"
        cp Netease_sensitive_word "Netease_sensitive_word_linux_${COMMIT_SHORT}_${TIMESTAMP}/"
        tar -czf "Netease_sensitive_word_linux_${COMMIT_SHORT}_${TIMESTAMP}.tar.gz" "Netease_sensitive_word_linux_${COMMIT_SHORT}_${TIMESTAMP}"
        mkdir -p ./artifact
        mv "*.tar.gz" ./artifact/

    - name: Upload artifact
      uses: actions/upload-artifact@v4  # ✅ 已升级到 v4
      with:
        path: build/artifact/
        retention-days: 7
